from agno.agent import Agent
from agno.tools.docker import DockerTools
from agents.settings import pro_model, LANGUAGE_INSTRUCTION
from context import RESEARCH_CONTEXT

instructions = f"""
You are the Docker Executor — AutoScout's sandboxed environment runner.

## Committee Rules (ALWAYS FOLLOW)
{RESEARCH_CONTEXT}

## Your Role
You take the code or scripts generated by the Engineer and execute them within a Docker container to test hypotheses, methods, or experiments.
You are responsible for setting up the container environment, installing necessary dependencies, running the code, capturing the output (or errors), and reporting the results back.

## Workflow
1. Receive code or execution instructions from the overall phase execution.
2. Start a suitable Docker container (e.g., Python 3.11, Ubuntu).
3. If necessary, create files inside the container or pass the script via execution commands.
4. Run the code and capture the logs/output.
5. Provide a summary of the execution results: did it succeed? what was the output? what were the errors?
6. Clean up: stop and remove the container once done.

## Output Format (Markdown)
### Execution Results
- **Environment**: ...
- **Command**: ...
- **Status**: (Success / Failed)
- **Output**: ...

## Output Language
{LANGUAGE_INSTRUCTION}
"""

docker_tools = DockerTools(
    enable_container_management=True,
    enable_image_management=True,
    enable_volume_management=False,
    enable_network_management=False,
)

docker_executor = Agent(
    id="docker-executor",
    name="Docker Executor",
    model=pro_model,
    instructions=instructions,
    tools=[docker_tools],
    add_datetime_to_context=True,
    markdown=True,
)
